Addnp
Chimoney/non-profit-donations pull request #13
Opened 2023-10-04 23:22 UTC by mynameissaraah

New verified Non-profits were added 
Payment information for some of the non profits were updated

2023-10-05 12:40 UTC, uchibeke commented on src/non-profits-data/index.ts
> +
Could you reference where this wallet addresses where gotten from?

2023-10-05 12:47 UTC, uchibeke requested changes

2023-10-05 12:47 UTC, uchibeke commented on src/non-profits-data/index.ts
> +        paymentID: 'Account No: 0019052855 - Sterling Bank Plc 0034611000 Diamond Bank Plc Account ',
Could you reference where this information was gotten from?

2023-10-05 12:47 UTC, uchibeke commented on src/non-profits-data/index.ts
> +        type: 'Mail',
For these new Payment methods, as part of your PR, could you update the readme and add a Types section in the format below? This ensures we have a standardized payment method list so people are not creating any method. Also if you check the API, notice you can get NP by payment type. So we need standard codes/names for the payment types we are adding and also need to document them.

```
### Payment Types
These are the existing payment types that support
- xrp
- interledger
- mobile-money
- airtime
- new-type 1
- new-type 2
- new-type3
```

Please include all existing and new methods to the readme.

2023-10-05 18:52 UTC, mynameissaraah commented on src/non-profits-data/index.ts
> +        type: 'Mail',
ok noted

2023-10-05 18:52 UTC, mynameissaraah commented on src/non-profits-data/index.ts
> +        paymentID: 'Account No: 0019052855 - Sterling Bank Plc 0034611000 Diamond Bank Plc Account ',
Should I reference it as a comment?

2023-10-05 18:53 UTC, uchibeke commented on src/non-profits-data/index.ts
> +        paymentID: 'Account No: 0019052855 - Sterling Bank Plc 0034611000 Diamond Bank Plc Account ',
Yes please. Thanks 🚀

2023-10-05 20:19 UTC, mynameissaraah commented on src/non-profits-data/index.ts
> +        paymentID: 'Account No: 0019052855 - Sterling Bank Plc 0034611000 Diamond Bank Plc Account ',
Done

2023-10-06 02:21 UTC, mynameissaraah commented on src/non-profits-data/index.ts
> +        type: 'Mail',
@uchibeke I have made the requested changes

2024-12-04 21:16 UTC, closed without merging